@startuml
top to bottom direction
skinparam packageStyle rectangle

actor "Customer" as User
rectangle "Authorization System" as AuthSystem {
}

rectangle DAB {
  usecase "Withdraw Money" as Withdraw
}

User --> Withdraw : "Request Withdrawal"
Withdraw --> AuthSystem : "Check Authorization"

@enduml