@startuml
left to right direction
 skinparam packageStyle rectangle

 actor "Customer" as User
 actor "Authorization System" as AuthSystem


 package DAB {
   usecase "Insert Visa card" as InsertCard
   usecase "Check Visa card" as CheckCard
   usecase "Provide identification code" as ProvidePIN
   usecase "Validation identification code" as ValidationPIN
   usecase "Request authorization" as Request
   usecase "Weekly balance" as Balance
   usecase "Provide amount" as Amount
   usecase "Validation amount" as ValidationAmount
   usecase "Balance update"
   usecase "cash delivery" as Cash
 }

 User --> InsertCard
 InsertCard <. CheckCard
 User --> ProvidePIN : "Enter code"
 ProvidePIN <. ValidationPIN : "extend"
 Request --> AuthSystem
 AuthSystem --> Balance : "Agreement ok"
 Amount --> User : "Ask amount"
 User --> Amount : "Enter amount"
 Amount <. ValidationAmount : extend
 ValidationAmount --> AuthSystem : "authorized amount"
 ValidationAmount ..> "Balance update" : include
 AuthSystem --> Cash
 Cash --> User
@enduml